In [49]:
#import dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.plotly as py
import plotly.graph_objs as go
#read csv file and create DF for population
state_population_df = pd.read_csv("../../../../resources/data/statepopulation.csv")
state_population_df.head()

       States  Population
0     Alabama   4,887,871
1      Alaska     737,438
2     Arizona   7,171,646
3    Arkansas   3,013,825
4  California  39,557,045

In [50]:
#read csv file and create DF for gun owners
gun_owners_df = pd.read_csv("../../../../resources/data/gunowners.csv")
state_population_df.head()

       States  Population
0     Alabama   4,887,871
1      Alaska     737,438
2     Arizona   7,171,646
3    Arkansas   3,013,825
4  California  39,557,045

In [51]:
#merge two df's on state 
state_vs_gunowners_df = pd.merge(state_population_df, gun_owners_df, on='States', how='inner')
#state_vs_gunowners= pd.DataFrame({'calcversionofpercapita': (int(state_vs_gunowners['# of guns registered'])*1000)/int(state_vs_gunowners['Population'])})
state_vs_gunowners_df.head()

       States  Population  Rank  # of guns per capita # of guns registered
0     Alabama   4,887,871     6                 33.15              161,641
1      Alaska     737,438    15                 21.38               15,824
2     Arizona   7,171,646    10                 25.61              179,738
3    Arkansas   3,013,825     8                 26.57               79,841
4  California  39,557,045    44                  8.71              344,622

In [52]:
#read incidents file and merge with the above to DF to get incidents count by state 
incidents_by_state_df = pd.read_csv("../../../../resources/data/inc_dt_reg_lat_lon.csv")
incidents_by_state_df = pd.DataFrame({'IncidentsCount': incidents_by_state_df.groupby(['state'])['incident_id'].size()})
incidents_by_state_df = incidents_by_state_df.reset_index()
incidents_by_state_df.rename(columns={'state': 'States'}, inplace=True)
state_vs_gunowners_vs_inc_df = pd.merge(state_vs_gunowners_df, incidents_by_state_df, on='States', how='inner')
state_vs_gunowners_vs_inc_df.head()
state_vs_gunowners_vs_inc_df.set_index('States', inplace=True)
state_vs_gunowners_vs_inc_df["Population"] = state_vs_gunowners_vs_inc_df["Population"].str.replace(",","").astype(float)
state_vs_gunowners_vs_inc_df["# of guns registered"] = state_vs_gunowners_vs_inc_df["# of guns registered"].str.replace(",","").astype(float)
#state_vs_gunowners_vs_inc_df= pd.DataFrame({'calcversionofpercapita': (state_vs_gunowners_vs_inc_df['# of guns registered'])*1000/state_vs_gunowners_vs_inc_df['Population']})
state_vs_gunowners_vs_inc_df["calcversionofpercapita"] = (state_vs_gunowners_vs_inc_df['# of guns registered'])*1000/state_vs_gunowners_vs_inc_df['Population']
state_vs_gunowners_vs_inc_df = state_vs_gunowners_vs_inc_df.reset_index()
state_vs_gunowners_vs_inc_df

,States,Population,Rank,# of guns per capita,# of guns registered,IncidentsCount,calcversionofpercapita
0,Alabama,4887871.0,6,33.150,161641.0,5471,33.069817
1,Alaska,737438.0,15,21.380,15824.0,1349,21.458075
2,Arizona,7171646.0,10,25.610,179738.0,2328,25.062308
3,Arkansas,3013825.0,8,26.570,79841.0,2842,26.491585
4,California,39557045.0,44,8.710,344622.0,16306,8.712026
5,Colorado,5695564.0,28,16.480,92435.0,3201,16.229297
6,Connecticut,3572665.0,14,22.960,82400.0,3067,23.064015
7,Delaware,967171.0,49,5.040,4852.0,1685,5.016693
8,Florida,21299325.0,29,16.350,343288.0,15029,16.117318
9,Georgia,10519475.0,21,18.220,190050.0,8925,18.066491
10,Hawaii,1420491.0,47,5.500,7859.0,289,5.532594
11,Idaho,1754208.0,7,28.860,49566.0,661,28.255486
12,Illinois,12741080.0,40,11.440,146487.0,17556,11.497220
13,Indiana,6691878.0,26,17.100,114019.0,5852,17.038416
14,Iowa,3156145.0,43,9.050,28494.0,2517,9.028102
15,Kansas,2911505.0,24,18.060,52634.0,2145,18.077936
16,Kentucky,4468402.0,22,18.200,81068.0,4157,18.142504
17,Louisiana,4659978.0,11,24.940,116831.0,8103,25.071148
18,Maine,1338404.0,39,11.500,15371.0,907,11.484574
19,Maryland,6042718.0,27,17.030,103109.0,5798,17.063348
20,Massachusetts,6902149.0,48,5.410,37152.0,5981,5.382671
21,Michigan,9995915.0,45,6.590,65742.0,6136,6.576887
22,Minnesota,5611179.0,34,14.220,79307.0,2408,14.133750
23,Mississippi,2986530.0,37,11.890,35494.0,3599,11.884696
24,Missouri,6126452.0,36,11.940,72996.0,6631,11.914890
25,Montana,1062305.0,16,21.060,22133.0,638,20.834883
26,Nebraska,1929268.0,38,11.570,22234.0,1651,11.524578
27,Nevada,3034392.0,9,25.640,76888.0,1952,25.338849
28,New Hampshire,1356458.0,3,46.760,64135.0,964,47.281228
29,New Jersey,8908520.0,46,6.380,57507.0,5387,6.455281
30,New Mexico,2095428.0,4,46.730,97580.0,1645,46.568052
31,New York,19542209.0,51,3.830,76207.0,9712,3.899610
32,North Carolina,10383620.0,31,14.818,152238.0,8739,14.661361
33,North Dakota,760077.0,25,17.560,13272.0,573,17.461389
34,Ohio,11689442.0,30,14.870,173405.0,10244,14.834327
35,Oklahoma,3943079.0,23,18.130,71269.0,3455,18.074454
36,Oregon,4190713.0,32,14.816,61383.0,2286,14.647388
37,Pennsylvania,12807060.0,20,18.450,236377.0,8929,18.456773
38,Rhode Island,1057315.0,50,3.980,37152.0,895,35.138062
39,South Carolina,5084127.0,17,21.010,105601.0,6939,20.770724
40,South Dakota,882235.0,12,24.290,21130.0,544,23.950535
41,Tennessee,6770010.0,33,14.760,99159.0,7626,14.646803
42,Texas,28701845.0,18,20.790,588696.0,13577,20.510737
43,Utah,3161105.0,13,23.480,72856.0,1072,23.047637
44,Vermont,626299.0,42,9.410,5872.0,472,9.375714
45,Virginia,8517685.0,5,36.340,307822.0,5949,36.139162
46,Washington,7535591.0,35,12.400,91835.0,3434,12.186834
47,West Virginia,1805832.0,19,19.420,35264.0,1575,19.527841
48,Wisconsin,5813568.0,41,11.190,64878.0,4787,11.159756
49,Wyoming,577737.0,1,229.240,132806.0,494,229.872762

In [74]:
#plot the graph against pop vs inc vs guns registered
#ax = state_vs_gunowners_vs_inc_df[['Population','# of guns registered','IncidentsCount']].plot(kind='bar',stacked=True, title ="pop vs in vs gun registered", figsize=(20, 10), legend=True, fontsize=12)
#ax.set_xlabel("States", fontsize=12)
#ax.set_ylabel("Counts of Incidents", fontsize=12)
#plt.show()
x=state_vs_gunowners_vs_inc_df['calcversionofpercapita']*1000
y=state_vs_gunowners_vs_inc_df['IncidentsCount']
size=y*0.006
scl = [[0.0, 'rgb(242,240,247)'],[0.2, 'rgb(218,218,235)'],[0.4, 'rgb(188,189,220)'],\
            [0.6, 'rgb(158,154,200)'],[0.8, 'rgb(117,107,177)'],[1.0, 'rgb(84,39,143)']]
trace0 = go.Scatter(
    x=x,
    y=y,
    text=state_vs_gunowners_vs_inc_df['States'],
    mode='markers',
    marker=dict(
        color=['rgb(255, 255, 255)'],
        size=size,
       )
)
layout = go.Layout(
    title='Incidents Count Vs Per Capita for last 5 yrs',
    xaxis=dict(
        title='Per Capita',
        titlefont=dict(
            family='Courier New, monospace',
            size=18,
            color='#7f7f7f'
        )
    ),
    yaxis=dict(
        title='Incidents Counts',
        titlefont=dict(
            family='Courier New, monospace',
            size=18,
            color='#7f7f7f'
        )
    )
)
data = [trace0]
fig = go.Figure(data=data, layout=layout)
py.iplot(fig ,filename='bubblechart-color')